# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: ticketmachine  # Checkout apenas a pasta ticketmachine
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: ticketmachine  # Define o diretório de trabalho para ticketmachine
      run: mvn -B package
    - name: Update dependency graph
      working-directory: $GITHUB_WORKSPACE/ticketmachine  # Define o diretório de trabalho para ticketmachine usando $GITHUB_WORKSPACE
      run: mvn com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
